server {
    listen 80;
    server_name pentime-new.com www.pentime-new.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pentime-new.com www.pentime-new.com;

    root /usr/share/nginx/html/pentime-updates;
    index index.html;
    client_max_body_size 0;

    ssl_certificate /etc/nginx/ssl/pentime-new.com.pem;
    ssl_certificate_key /etc/nginx/ssl/pentime-new.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        add_header Access-Control-Allow-Origin "*" always;
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(yml|yaml|json)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Access-Control-Allow-Origin "*" always;
        try_files $uri =404;
    }
}
